### PR TITLE
Made code nicer and cleaner

### PR DESCRIPTION
**Pull request by mwisnia97**
**Description**
As a dev, I want to see clean code with eng convention.

**Changes**
- Used prettier to formate code
- Replace unnecessary SCSS on CSS
- Added background color on mobile menu

### CODE REVIEW

**Comment by mwisnia97** [comment]
If you have any questions please comment, we can discuss changes. 😊

**Comment by mwisnia97** [comment]
You don't need package-lock.json, package.json and node-modules, you are using simple HTML, CSS and JS. 😊

**Comment by dzalewski243** [comment]
Thanks for checking my code. What are the next stages of recruitment?

**Comment by mwisnia97** [comment]
Idk, I'm not a recruiter. I found your GitHub on the Facebook group and I just reviewed your code. 😊

**Comment by dzalewski243** [comment]
Got it, thanks. I will save your changes locally (for my own use), but I will post my code here again - unchanged as it was before. I thought you were a recruiter 😅

**Comment by mwisnia97** [comment]
Download repo as zip and make new repository only with your code, it will be better I think. 😊

**Pull request merged**
